<a href="https://colab.research.google.com/github/Kusuma0414/Kusuma0414/blob/main/CIE_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
print(df)

     Unnamed: 0            City         Country  Population (2024)  \
0             0           Tokyo           Japan           37115035   
1             1           Delhi           India           33807403   
2             2        Shanghai           China           29867918   
3             3           Dhaka      Bangladesh           23935652   
4             4       Sao Paulo          Brazil           22806704   
..          ...             ...             ...                ...   
796         796       Bhavnagar           India             751493   
797         797       Sheffield  United Kingdom             751303   
798         798          Huambo          Angola             751297   
799         799  Ribeirao Preto          Brazil             750174   
800         800       Panzhihua           China             750036   

     Population (2023)  Growth Rate  
0             37194105      -0.0021  
1             32941309       0.0263  
2             29210808       0.0225  
3      

In [27]:
df.describe()

Unnamed: 0  Population (2024)  Population (2023)  Growth Rate
count  801.000000       8.010000e+02       8.010000e+02   801.000000
mean   400.000000       2.654327e+06       2.604461e+06     0.020051
std    231.373075       3.723253e+06       3.661201e+06     0.012180
min      0.000000       7.500360e+05       7.228360e+05    -0.024900
25%    200.000000       9.909310e+05       9.698040e+05     0.012200
50%    400.000000       1.379368e+06       1.363510e+06     0.019700
75%    600.000000       2.570980e+06       2.514077e+06     0.026600
max    800.000000       3.711504e+07       3.719410e+07     0.058200

In [3]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
data=df.dropna()
print(data)

     Unnamed: 0            City         Country  Population (2024)  \
0             0           Tokyo           Japan           37115035   
1             1           Delhi           India           33807403   
2             2        Shanghai           China           29867918   
3             3           Dhaka      Bangladesh           23935652   
4             4       Sao Paulo          Brazil           22806704   
..          ...             ...             ...                ...   
796         796       Bhavnagar           India             751493   
797         797       Sheffield  United Kingdom             751303   
798         798          Huambo          Angola             751297   
799         799  Ribeirao Preto          Brazil             750174   
800         800       Panzhihua           China             750036   

     Population (2023)  Growth Rate  
0             37194105      -0.0021  
1             32941309       0.0263  
2             29210808       0.0225  
3      

In [4]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
data=df.dropna(axis=1)
print(data)

     Unnamed: 0            City         Country  Population (2024)  \
0             0           Tokyo           Japan           37115035   
1             1           Delhi           India           33807403   
2             2        Shanghai           China           29867918   
3             3           Dhaka      Bangladesh           23935652   
4             4       Sao Paulo          Brazil           22806704   
..          ...             ...             ...                ...   
796         796       Bhavnagar           India             751493   
797         797       Sheffield  United Kingdom             751303   
798         798          Huambo          Angola             751297   
799         799  Ribeirao Preto          Brazil             750174   
800         800       Panzhihua           China             750036   

     Population (2023)  Growth Rate  
0             37194105      -0.0021  
1             32941309       0.0263  
2             29210808       0.0225  
3      

In [5]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
data=df.fillna(df.mean(numeric_only=True))
print(data)

     Unnamed: 0            City         Country  Population (2024)  \
0             0           Tokyo           Japan           37115035   
1             1           Delhi           India           33807403   
2             2        Shanghai           China           29867918   
3             3           Dhaka      Bangladesh           23935652   
4             4       Sao Paulo          Brazil           22806704   
..          ...             ...             ...                ...   
796         796       Bhavnagar           India             751493   
797         797       Sheffield  United Kingdom             751303   
798         798          Huambo          Angola             751297   
799         799  Ribeirao Preto          Brazil             750174   
800         800       Panzhihua           China             750036   

     Population (2023)  Growth Rate  
0             37194105      -0.0021  
1             32941309       0.0263  
2             29210808       0.0225  
3      

In [6]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
z_score=(df-df.mean(numeric_only=True))/df.std(numeric_only=True)
print(z_score)


    City Country  Growth Rate  Population (2023)  Population (2024)  \
0    NaN     NaN    -1.818646           9.447623           9.255537   
1    NaN     NaN     0.513024           8.286038           8.367165   
2    NaN     NaN     0.201040           7.267109           7.309089   
3    NaN     NaN     0.923529           5.627977           5.715788   
4    NaN     NaN    -0.964795           5.466861           5.412572   
..   ...     ...          ...                ...                ...   
796  NaN     NaN    -0.045263          -0.510033          -0.511068   
797  NaN     NaN    -1.046896          -0.507644          -0.511119   
798  NaN     NaN     1.022050          -0.512624          -0.511120   
799  NaN     NaN    -0.751332          -0.508671          -0.511422   
800  NaN     NaN    -0.365457          -0.509660          -0.511459   

     Unnamed: 0  
0     -1.728810  
1     -1.724488  
2     -1.720166  
3     -1.715844  
4     -1.711522  
..          ...  
796    1.711522  
797

In [12]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
numeric_data=df.select_dtypes(include='number')
rolling_mean=numeric_data.rolling(window=2).mean()
rolling_std=numeric_data.rolling(window=2).std()
outliers=numeric_data[(numeric_data-rolling_mean).abs()>-1*rolling_std]
print(outliers)

     Unnamed: 0  Population (2024)  Population (2023)  Growth Rate
0           NaN                NaN                NaN          NaN
1           1.0         33807403.0         32941309.0       0.0263
2           2.0         29867918.0         29210808.0       0.0225
3           3.0         23935652.0         23209616.0       0.0313
4           4.0         22806704.0         22619736.0       0.0083
..          ...                ...                ...          ...
796       796.0           751493.0           737128.0       0.0195
797       797.0           751303.0           745876.0       0.0073
798       798.0           751297.0           727641.0       0.0325
799       799.0           750174.0           742115.0       0.0109
800       800.0           750036.0           738495.0       0.0156

[801 rows x 4 columns]


In [14]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
numeric_data=df.select_dtypes(include='number')
upper_cap=40
lower_cap=5
data_clipped=numeric_data.clip(lower=lower_cap, upper=upper_cap)
data[data_clipped.columns]=data_clipped
print(data)



     Unnamed: 0            City         Country  Population (2024)  \
0             5           Tokyo           Japan                 40   
1             5           Delhi           India                 40   
2             5        Shanghai           China                 40   
3             5           Dhaka      Bangladesh                 40   
4             5       Sao Paulo          Brazil                 40   
..          ...             ...             ...                ...   
796          40       Bhavnagar           India                 40   
797          40       Sheffield  United Kingdom                 40   
798          40          Huambo          Angola                 40   
799          40  Ribeirao Preto          Brazil                 40   
800          40       Panzhihua           China                 40   

     Population (2023)  Growth Rate  
0                   40          5.0  
1                   40          5.0  
2                   40          5.0  
3      

In [15]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
numeric_data=df.select_dtypes(include='number')
data_log_transformtion=np.log(numeric_data)
print(data_log_transformtion)

     Unnamed: 0  Population (2024)  Population (2023)  Growth Rate
0          -inf          17.429533          17.431661          NaN
1      0.000000          17.336190          17.310238    -3.638186
2      0.693147          17.212295          17.190049    -3.794240
3      1.098612          16.990880          16.960077    -3.464137
4      1.386294          16.942565          16.934333    -4.791500
..          ...                ...                ...          ...
796    6.679599          13.529817          13.510517    -3.937341
797    6.680855          13.529564          13.522315    -4.919881
798    6.682109          13.529556          13.497563    -3.426515
799    6.683361          13.528060          13.517259    -4.518992
800    6.684612          13.527876          13.512370    -4.160484

[801 rows x 4 columns]


/usr/local/lib/python3.10/dist-packages/pandas/core/internals/blocks.py:366: RuntimeWarning: divide by zero encountered in log
  result = func(self.values, **kwargs)
/usr/local/lib/python3.10/dist-packages/pandas/core/internals/blocks.py:366: RuntimeWarning: invalid value encountered in log
  result = func(self.values, **kwargs)


In [16]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
numeric_data=df.select_dtypes(include='number')
outliers=[500]
data=df[~df.isin(outliers)]
print(data)

     Unnamed: 0            City         Country  Population (2024)  \
0           0.0           Tokyo           Japan           37115035   
1           1.0           Delhi           India           33807403   
2           2.0        Shanghai           China           29867918   
3           3.0           Dhaka      Bangladesh           23935652   
4           4.0       Sao Paulo          Brazil           22806704   
..          ...             ...             ...                ...   
796       796.0       Bhavnagar           India             751493   
797       797.0       Sheffield  United Kingdom             751303   
798       798.0          Huambo          Angola             751297   
799       799.0  Ribeirao Preto          Brazil             750174   
800       800.0       Panzhihua           China             750036   

     Population (2023)  Growth Rate  
0             37194105      -0.0021  
1             32941309       0.0263  
2             29210808       0.0225  
3      

In [17]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
data=df.drop_duplicates()
print(data)


     Unnamed: 0            City         Country  Population (2024)  \
0             0           Tokyo           Japan           37115035   
1             1           Delhi           India           33807403   
2             2        Shanghai           China           29867918   
3             3           Dhaka      Bangladesh           23935652   
4             4       Sao Paulo          Brazil           22806704   
..          ...             ...             ...                ...   
796         796       Bhavnagar           India             751493   
797         797       Sheffield  United Kingdom             751303   
798         798          Huambo          Angola             751297   
799         799  Ribeirao Preto          Brazil             750174   
800         800       Panzhihua           China             750036   

     Population (2023)  Growth Rate  
0             37194105      -0.0021  
1             32941309       0.0263  
2             29210808       0.0225  
3      

In [18]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
data=df.drop_duplicates(subset=['City'])
print(data)

     Unnamed: 0            City         Country  Population (2024)  \
0             0           Tokyo           Japan           37115035   
1             1           Delhi           India           33807403   
2             2        Shanghai           China           29867918   
3             3           Dhaka      Bangladesh           23935652   
4             4       Sao Paulo          Brazil           22806704   
..          ...             ...             ...                ...   
796         796       Bhavnagar           India             751493   
797         797       Sheffield  United Kingdom             751303   
798         798          Huambo          Angola             751297   
799         799  Ribeirao Preto          Brazil             750174   
800         800       Panzhihua           China             750036   

     Population (2023)  Growth Rate  
0             37194105      -0.0021  
1             32941309       0.0263  
2             29210808       0.0225  
3      

In [20]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
data=df.select_dtypes(include='number').values
scaler=MinMaxScaler()
normalized=scaler.fit_transform(data)
print(normalized)

[[0.00000000e+00 1.00000000e+00 1.00000000e+00 2.74368231e-01]
 [1.25000000e-03 9.09043528e-01 8.83393254e-01 6.16125150e-01]
 [2.50000000e-03 8.00711750e-01 7.81107233e-01 5.70397112e-01]
 ...
 [9.97500000e-01 3.46762006e-05 1.31747541e-04 6.90734055e-01]
 [9.98750000e-01 3.79485780e-06 5.28607875e-04 4.30806258e-01]
 [1.00000000e+00 0.00000000e+00 4.29351663e-04 4.87364621e-01]]


In [21]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
data=df.select_dtypes(include='number')
scaler=StandardScaler()
standard=scaler.fit_transform(data)
print(standard)

[[-1.7298898   9.2613197   9.45352553 -1.81978222]
 [-1.72556507  8.37239316  8.29121475  0.51334449]
 [-1.72124035  7.31365605  7.27164986  0.20116556]
 ...
 [ 1.72124035 -0.51143965 -0.51294451  1.02268905]
 [ 1.72556507 -0.51174146 -0.50898869 -0.75180168]
 [ 1.7298898  -0.51177854 -0.50997806 -0.36568564]]


In [23]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
binary=pd.get_dummies(df['Population (2023)'])
print(binary)


     722836    727641    729276    729768    733810    734699    737128    \
0       False     False     False     False     False     False     False   
1       False     False     False     False     False     False     False   
2       False     False     False     False     False     False     False   
3       False     False     False     False     False     False     False   
4       False     False     False     False     False     False     False   
..        ...       ...       ...       ...       ...       ...       ...   
796     False     False     False     False     False     False      True   
797     False     False     False     False     False     False     False   
798     False      True     False     False     False     False     False   
799     False     False     False     False     False     False     False   
800     False     False     False     False     False     False     False   

     738200    738495    738552    ...  19013434  21296517  21766214  \
0  

In [24]:
import pandas as pd
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
ranked=df['City'].rank()
print(ranked)

0      693.0
1      192.0
2      622.0
3      198.0
4      612.0
       ...  
796     91.0
797    630.0
798    291.0
799    581.0
800    533.0
Name: City, Length: 801, dtype: float64


In [25]:
import pandas as pd
from sklearn.decomposition import PCA
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
numeric_data=df.select_dtypes(include='number')
array=numeric_data.values
pca=PCA(n_components=2)
reduced_data=pca.fit_transform(array)
print('orginial data shape:', array.shape)
print('reduce data shape:', reduced_data.shape)

orginial data shape: (801, 4)
reduce data shape: (801, 2)


In [26]:
import pandas as pd
from sklearn.manifold import TSNE
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
numeric_data=df.select_dtypes(include='number')
X=numeric_data.values
tsne=TSNE(n_components=2, random_state=42)
t_sne=tsne.fit_transform(array)
print(' t_sne data shape:', t_sne.shape)


 t_sne data shape: (801, 2)


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/World Largest Cities by Population 2024.csv')
mean=np.mean(df.select_dtypes(include='number'), axis=0)
cov_matrix=np.cov(df.select_types(include='number'), rowvar=False)